### PR TITLE
#166980201 Setup testing environment

### PR DESCRIPTION
**Pull request by jmusila**
#### What does this PR do?
- sets up a testing environment

#### Description of the tasks to be completed?
- [x] install necessary dependencies
- [x] add a test script
- [x] configure enzyme and jest
- [x] write a sample test

#### How should this be manually tested?
- clone the repo `$ git clone https://github.com/andela/ah-baqi-frontend.git`
- install dependencies `$ yarn`
- run the test `yarn test` or `yarn run test`
- to run test coverage `yarn test --coverage`

#### Any background context you want to provide?
- None

#### What are the relevant pivotal tracker stories?
#166980201

#### Screenshots (if appropriate)
Screenshot 2019-07-02 at 15 34 05

### CODE REVIEW

**Comment by ceexon** [comment]
LGTM 👍

**Review by ceexon — APPROVED** [review]

**Review by willeswa — APPROVED** [review]

**Review by wangonya — CHANGES_REQUESTED** [review]
You can also add `"test:cov": "jest --coverage"` to make testing with coverage easier for us 😄

**Comment by jmusila** [comment]
> You can also add `"test:cov": "jest --coverage"` to make testing with coverage easier for us 😄

Done 👍

**Review by wangonya — APPROVED** [review]

**Comment by FlevianK** [comment]
LGTM

**Pull request merged**
